# Generated by Django 4.0.6 on 2022-07-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='descriptions',
            new_name='description',
        ),
    ]
